name: deploy1

on:
  push:
    branches: [ master ]

jobs:
  build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash
        
      - name: Build with Gradle
        uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
        with:
          arguments: build


      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy


        # Jar 파일 복사
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy

      # appspec.yml 파일 복사
      - name: Copy appspec.yml
        run: cp appspec.yml ./deploy

      - name: Copy script
        run: cp ./scripts/*.sh ./deploy

        # 파일 압축
      - name: Make zip file
        run: zip -r ./$GITHUB_SHA.zip ./deploy

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY  }}
          aws-region: ap-northeast-2


      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://ghwns6743/$GITHUB_SHA.zip

      - name: Deploy
        run: aws deploy create-deployment --application-name ghwns6743 --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name ghwns6743 --s3-location bucket=ghwns6743,bundleType=zip,key=$GITHUB_SHA.zip  

        
